language: csharp
mono: none
dotnet: 5.0.301
solution: dotnetCore.sln

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test test-library/test-library.csproj
  - dotnet dotnet publish -c Release